import type { CatalogSettings } from "../features/library/client";
import { DEFAULT_SHORTCUTS } from "../features/input/shortcuts";
import { DEFAULT_VIEWER_QUADRANT_BINDINGS } from "../features/input/viewer-quadrants";
import { DEFAULT_MOUSE_GESTURES } from "../features/settings/profile";
import type { CatalogEntry } from "../types/domain";

/** A readable archive entry for App-level tests. */
export function testArchiveEntry(relativePath: string): CatalogEntry {
  return {
    relativePath: relativePath as never,
    kind: "archive",
    archiveKind: "cbz",
  };
}

export const DEFAULT_CATALOG_SETTINGS: CatalogSettings = {
  sortField: "name",
  sortDescending: false,
  endOfVolumePolicy: "auto_next",
  catalogViewMode: "cover_list",
  catalogThumbnailSizes: { smallThumbnail: 104, coverList: 144, cardGrid: 216, referenceTile: 128 },
  viewMode: "single",
  spreadPortraitMaxAspectPercent: 100,
  autoSpreadMinViewportAspectPercent: 125,
  spreadFirstPageSingle: false,
  spreadPairing: "continuous",
  fitAllowUpscale: false,
  fitBasis: "spread",
  fitIncludePageMargin: true,
  readingDirection: "rightToLeft",
  scaleMode: "fit",
  scale: 1,
  loupeEnabled: false,
  loupeSize: 180,
  loupeZoom: 2,
  prefetchAhead: 4,
  prefetchBehind: 0,
  prefetchMemoryMiB: 256,
  fullscreenEscapeBehavior: "exitFullscreen",
  preventDisplaySleepFullscreen: false,
  trayStoreOnMinimize: false,
  trayCloseBehavior: "quit",
  trayRestoreGesture: "singleClick",
  slideshowIntervalMs: 3_000,
  slideshowOrder: "forward",
  slideshowRepeatCurrentItem: false,
  viewerCatalogSelectionSync: true,
  viewerBackground: "checker",
  viewerPageMargin: 0,
  viewerSpreadGap: 8,
  cursorAutoHideMs: 0,
  zoomRetention: "global",
  viewerGridEnabled: false,
  viewerGridSize: 32,
  viewerGridColor: "light",
  panFactor: 1,
  wheelDeadZone: 0,
  scrollStepPercent: 90,
  keyScrollAccelerationPercent: 150,
  keyScrollContinuous: true,
  smoothScroll: true,
  pageScanMode: "vertical",
  treeVisible: true,
  treeAutoCollapse: false,
  treeConfirmChildren: true,
  treeWidth: 240,
  treeHeight: 240,
  catalogPanePosition: "right",
  menuBarVisible: true,
  toolbarVisible: true,
  addressBarVisible: true,
  statusBarVisible: true,
  alwaysOnTop: false,
  themeSelection: { kind: "system" },
  customThemeSnapshot: null,
  themeFallbackReason: null,
  navigationSelectionPolicy: "restore",
  thumbnailGenerationScope: "near",
  startupLocation: "last",
  showHiddenFiles: false,
  restoreLastViewer: false,
    autoRefreshCurrentFolder: true,
    folderOpenRule: "navigate",
    imageOpenRule: "read",
    archiveOpenRule: "read",
    detailGridLines: "none",
    detailRowDensity: "standard",
    detailShowKind: true,
    detailShowSize: true,
    detailShowModified: true,
  shortcuts: { ...DEFAULT_SHORTCUTS },
  catalogMouseBindings: {
    primaryClick: "selectOnly",
    doubleClick: "openSelected",
    middleClick: "none",
    backButton: "navigateBack",
    forwardButton: "navigateForward",
  },
  viewerQuadrantBindings: { ...DEFAULT_VIEWER_QUADRANT_BINDINGS },
  viewerRightClickAction: "none",
  mouseGestures: { ...DEFAULT_MOUSE_GESTURES },
};
